server:
  port: 8989
spring:  
 application: 
     name: GETEWAY-SERVER       
 cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVER
          uri: lb://DEPARTMENT-SERVER
          predicates:
            - Path=/department/**   
        - id: EMPOLOYEE-SERVER
          uri: lb://EMPOLOYEE-SERVER
          predicates:
            - Path=/Employeeservices/**       
                          
     
eureka: 
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance: 
   hostname: localhost

     
    
 
   
  