--- 
eureka: 
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka/"
  instance: 
   hostname: localhost
server: 
  port: 9001
spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    password: ~
    url: "jdbc:mysql://localhost:3306/userservices"
    username: root
  application: 
    name: EMPOLOYEE-SERVER  
  jpa: 
    generate-ddl: false
    hibernate.ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
ribbon:
  eureka:
    enabled: false
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
      ignoreExceptions:
          - com.example.serviceapplication.employee.Demoservices.Dao.MyException    

resilience4j.ratelimiter:
  instances:
    service1:
      limitForPeriod: 10
      limitRefreshPeriod: 100000
      timeoutDuration: 1000ms

resilience4j.retry:
  instances:
    retryService1:
      maxRetryAttempts: 5
      waitDuration: 10000  

